#!/usr/bin/env bash

PATH_BB8=$(command -v bb8)
if [ $? -ne 0 ]; then
    echo "Error: bb8 is not installed."
    exit 1
fi

PATH_BARMAN_MONTAGU=$(command -v barman-montagu)
if [ $? -ne 0 ]; then
    echo "Error: barman-montagu is not installed."
    exit 1
fi

ROOT_BARMAN_MONTAGU=$(dirname $(readlink $PATH_BARMAN_MONTAGU))
LOGDIR="$ROOT_BARMAN_MONTAGU/logs"
LOGPATH="$ROOT_BARMAN_MONTAGU/logs/barman.log"

echo "Found bb8 at: $PATH_BB8"
echo "Found barman-montagu at: $PATH_BARMAN_MONTAGU"
echo "Logging to: $LOGDIR"

if [ ! -f $LOGPATH ]; then
    mkdir -p $LOGDIR
    touch $LOGPATH
    chown -R montagu.montagu $LOGDIR
fi

DEST=/etc/cron.daily/barman-monatgu-nightly

echo "Writing cron job to $DEST"
cat <<EOF > "$DEST"
#!/usr/bin/env bash
set -e
exec &>> $LOGPATH
$PATH_BARMAN_MONTAGU update-nightly
$PATH_BB8 backup
EOF

echo "Creating logrotate configuration"
cat <<EOF > /etc/logrotate.d/barman
$LOGPATH {
  rotate 3
  weekly
  compress
  delaycompress
  missingok
  notifempty
  create 644 montagu montagu
}
EOF

echo "You can test this by running"
echo
echo "    run-parts -v --test /etc/cron.daily"
